apiVersion: v1	
kind: Service	
metadata:	
  name: heart-disease-flask-app
  labels:
    run: heart-disease-flask-app
spec:	
  ports:
  - protocol: TCP
    port: 80	
    targetPort: 80
  selector:	
    app: nginx


apiVersion: v1	
kind: Service	
metadata:	
  name: nginx
  labels:
    run: heart-disease-flask-app
spec:	
  ports:
  - protocol: TCP
    port: 80	
    targetPort: 80
  selector:	
    app: nginx
